title: Trabajos pr치cticos (Programaci칩n II)
description: >
  Consignas de los trabajos pr치cticos de Programaci칩n II. Instituto de
  Ciencias, Universidad Nacional de General Sarmiento (Argentina).
baseurl: "/tps"
url: "https://ungs-prog2.github.io"

# Build settings
theme: minima
markdown: kramdown
permalink: pretty

kramdown:
  footnote_backlink: "&#x21A9;&#xFE0E;"

collections:
  tps:
    output: true
    permalink: /:path/

exclude: ["Gemfile"]

defaults:
  -
    scope:
      path: ""
      type: "tps"
    values:
      layout: tp
